Repository DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD, pull requests merged in 2022-11, with the labels that each got.

#45 BD-94-workday-entity-시간-형식-수정
  Rlog/CoreData/DataModel.xcdatamodeld/Rlog.xcdatamodel/contents
  Rlog/Model/CoreData/WorkDayEntity+CoreDataProperties.swift
Labels: 머지 요청

#46 BD-93-월별-모든-workday-가져오는-함수-추가
  Rlog/CoreData/CoreDataManager.swift
Labels: 머지 요청

#48 Bd 99 custom model 사용 구현
  Rlog.xcodeproj/project.pbxproj
  Rlog/Extension/ScheduleListView+.swift
  Rlog/Model/WorkDay.swift
  Rlog/View/Schedule/ScheduleListView.swift
  Rlog/View/Schedule/ScheduleUpdateView.swift
  Rlog/ViewModel/Schedule/ScheduleCreateViewModel.swift
  Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
  Rlog/ViewModel/Schedule/ScheduleUpdateViewModel.swift
Labels: 리뷰 요청

#47 BD-100-workday-entity-work-type-attributes-추가
  Rlog.xcodeproj/project.pbxproj
  Rlog/CoreData/CoreDataManager.swift
  Rlog/CoreData/DataModel.xcdatamodeld/Rlog.xcdatamodel/contents
  Rlog/Model/CoreData/WorkDayEntity+CoreDataProperties.swift
  Rlog/Model/WorkDayType.swift
  Rlog/ViewModel/Schedule/ScheduleCreateViewModel.swift
  Rlog/ViewModel/Schedule/ScheduleUpdateViewModel.swift
Labels: 리뷰 요청

#51 Bd 102 work day entity 변경에 따른 schedule 관리 부분 수정
  Rlog/CoreData/CoreDataManager.swift
  Rlog/Extension/ScheduleListView+.swift
  Rlog/Model/WorkDay.swift
  Rlog/View/Schedule/ScheduleUpdateView.swift
  Rlog/ViewModel/Schedule/ScheduleCreateViewModel.swift
  Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
  Rlog/ViewModel/Schedule/ScheduleUpdateViewModel.swift
Labels: 리뷰 요청

#52 BD-103-work-day-entity-의-spent-hour-을-int-16-double-로-수정
  Rlog/CoreData/CoreDataManager.swift
  Rlog/CoreData/DataModel.xcdatamodeld/Rlog.xcdatamodel/contents
  Rlog/Model/CoreData/WorkDayEntity+CoreDataProperties.swift
Labels: 리뷰 요청, Conflict 발생

#53 refactor : BD-102 WorkDay Model 수정
  Rlog/Model/WorkDay.swift
  Rlog/ViewModel/Schedule/ScheduleCreateViewModel.swift
  Rlog/ViewModel/Schedule/ScheduleUpdateViewModel.swift
Labels: 리뷰 요청

#61 Bd 98 사유 작성 시 화면 가림 수정
  Rlog/View/Schedule/ScheduleCreateView.swift
  Rlog/View/Schedule/ScheduleUpdateView.swift
Labels: 리뷰 요청

#62 Bd 96 스케줄 확인 추가 및 삭제 시 화면 업데이트
  Rlog/Extension/ScheduleListView+.swift
  Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
Labels: 리뷰 요청

#65 Bd 97 미래 스케줄 더미 구현
  Rlog/CoreData/CoreDataManager.swift
  Rlog/Extension/Date+.swift
  Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
Labels: 리뷰 요청

#68 refactor : 2차 디자인 버전으로 인한 컬러 변경 및 로고 추가
  Rlog/Assets.xcassets/AppIcon.appiconset/Contents.json
  Rlog/Assets.xcassets/AppIcon.appiconset/RlogLogo.png
  Rlog/Assets.xcassets/AppIcon.appiconset/appLogo.png
  Rlog/Assets.xcassets/Background.colorset/Contents.json
  Rlog/Assets.xcassets/CardBackground.colorset/Contents.json
  Rlog/Assets.xcassets/Colors/BG_Card.colorset/Contents.json
  Rlog/Assets.xcassets/Colors/BG_Stroke.colorset/Contents.json
  Rlog/Assets.xcassets/Colors/BG_White.colorset/Contents.json
  Rlog/Assets.xcassets/Colors/Black.colorset/Contents.json
  Rlog/Assets.xcassets/Colors/Contents.json
  Rlog/Assets.xcassets/Colors/Gray_Dark.colorset/Contents.json
  Rlog/Assets.xcassets/Colors/Gray_Light.colorset/Contents.json
  Rlog/Assets.xcassets/Colors/Gray_Medium.colorset/Contents.json
  Rlog/Assets.xcassets/Colors/PointColor_Blue.colorset/Contents.json
  Rlog/Assets.xcassets/Colors/PointColor_Purple.colorset/Contents.json
  Rlog/Assets.xcassets/Colors/PointColor_Red.colorset/Contents.json
  Rlog/Assets.xcassets/Colors/Primary.colorset/Contents.json
  Rlog/Assets.xcassets/GradientGray.colorset/Contents.json
  Rlog/Assets.xcassets/Wip.imageset/Contents.json
  Rlog/Assets.xcassets/Wip.imageset/wipImage.png
  Rlog/Extension/Color+.swift
  Rlog/Extension/ScheduleListView+.swift
  Rlog/View/Components/FilledButton.swift
  Rlog/View/Components/StrokeButton.swift
  Rlog/View/Schedule/ScheduleCreateView.swift
  Rlog/View/Schedule/ScheduleListView.swift
  Rlog/View/Schedule/ScheduleUpdateView.swift
  Rlog/View/WorkSpace/SubViews/WorkSpaceCell.swift
  Rlog/View/WorkSpace/SubViews/WorkSpaceInfoSubView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateConfirmationView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateCreatingScheduleView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateScheduleListView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateView.swift
  Rlog/View/WorkSpace/WorkSpaceDetailView.swift
  Rlog/View/WorkSpace/WorkSpaceListView.swift
  Rlog/ViewModel/Schedule/ScheduleCreateViewModel.swift
  Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
Labels: 머지 요청

#66 BD-104-get-work-days-for-a-month-함수-만들기
  Rlog/CoreData/CoreDataManager.swift
Labels: 리뷰 요청

#76 Bd 123 컴포넌트 변경 디자인 반영
  Rlog.xcodeproj/project.pbxproj
  Rlog/View/Components/BorderedTextField.swift
  Rlog/View/Components/InputFormElement.swift
  Rlog/View/Components/UnderlinedTextField.swift
  Rlog/View/WorkSpace/WorkSpaceCreateCreatingScheduleView.swift
Labels: 어프루브 요청

#77 feat : 에셋 아이콘 추가 및 적용
  Rlog/Assets.xcassets/Icons/Contents.json
  Rlog/Assets.xcassets/Icons/calender.clock.imageset/Contents.json
  Rlog/Assets.xcassets/Icons/calender.clock.imageset/calendar-clock.svg
  Rlog/Assets.xcassets/Icons/coin.imageset/Contents.json
  Rlog/Assets.xcassets/Icons/coin.imageset/coin.svg
  Rlog/Assets.xcassets/Icons/inbox.curved.badge.imageset/Contents.json
  Rlog/Assets.xcassets/Icons/inbox.curved.badge.imageset/Group 194.svg
  Rlog/Assets.xcassets/Icons/inbox.curved.imageset/Contents.json
  Rlog/Assets.xcassets/Icons/inbox.curved.imageset/inbox.svg
  Rlog/Assets.xcassets/Icons/plus.curved.imageset/Contents.json
  Rlog/Assets.xcassets/Icons/plus.curved.imageset/plus.svg
  Rlog/Assets.xcassets/Icons/suitcase.imageset/Contents.json
  Rlog/Assets.xcassets/Icons/suitcase.imageset/suitcase.svg
  Rlog/Model/Tab.swift
  Rlog/View/MainTabView.swift
  Rlog/View/WorkSpace/WorkSpaceListView.swift
Labels: 어프루브 요청

#73 BD-134 : CoreData - Entity 작성
  Rlog.xcodeproj/project.pbxproj
  Rlog/CoreData/DataModel.xcdatamodeld/DataModel.xcdatamodel/contents
  Rlog/CoreData/Model/ScheduleEntity+CoreDataClass.swift
  Rlog/CoreData/Model/ScheduleEntity+CoreDataProperties.swift
  Rlog/CoreData/Model/WorkdayEntity+CoreDataClass.swift
  Rlog/CoreData/Model/WorkdayEntity+CoreDataProperties.swift
  Rlog/CoreData/Model/WorkspaceEntity+CoreDataClass.swift
  Rlog/CoreData/Model/WorkspaceEntity+CoreDataProperties.swift
Labels: 머지 요청, Conflict 발생

#74 Bd 23 cell 제외 UI 구현 전체 정산 달
  Rlog/Extension/Date+.swift
  Rlog/View/MonthlyCalculate/MonthlyCalculateListView.swift
  Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateListViewModel.swift
Labels: 어프루브 요청

#75 Bd 117 UI 변동사항 간격 컬러 등 반영
  Rlog/View/WorkSpace/SubViews/WorkSpaceCell.swift
  Rlog/View/WorkSpace/WorkSpaceListView.swift
Labels: 리뷰 요청

#82 Bd 168 CoreData - CoreDataManager CRUD 로직 작성
  Rlog/CoreData/CoreDataManager.swift
  Rlog/CoreData/DataModel.xcdatamodeld/DataModel.xcdatamodel/contents
  Rlog/CoreData/Model/ScheduleEntity+CoreDataProperties.swift
  Rlog/CoreData/Model/WorkdayEntity+CoreDataProperties.swift
  Rlog/CoreData/Model/WorkspaceEntity+CoreDataProperties.swift
Labels: 리뷰 요청

#83 BD-172 디자인 디테일 수정
  Rlog/View/Components/HDivider.swift
  Rlog/View/Schedule/ScheduleListView.swift
Labels: 리뷰 요청

#80 Bd 140 정산 결과 UI 구현
  Rlog.xcodeproj/project.pbxproj
  Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift
  Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateDetailViewModel.swift
Labels: 어프루브 요청

#81 BD-174 SchedulePendingListView UI
  Rlog.xcodeproj/project.pbxproj
  Rlog/View/Schedule/ScheduleListView.swift
  Rlog/View/Schedule/SchedulePendingListView.swift
  Rlog/ViewModel/Schedule/SchedulePendingListViewModel.swift
Labels: 어프루브 요청

#85 BD-175 근무 카드 디자인 수정
  Rlog/View/Schedule/ScheduleCell.swift
  Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
Labels: 리뷰 요청

#84 Bd 142 상세 정보 cell UI 구현
  Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift
Labels: 어프루브 요청

#89 Bd 160 schedule creation view bordered picker pr update
  Rlog.xcodeproj/project.pbxproj
  Rlog/View/Components/BorderedPicker.swift
  Rlog/View/Schedule/ScheduleCreationView.swift
  Rlog/View/Schedule/ScheduleListView.swift
  Rlog/View/Schedule/SchedulePendingListView.swift
  Rlog/ViewModel/Schedule/ScheduleCreationViewModel.swift
Labels: 리뷰 요청

#87 BD-153 근무지 생성 flow 연결했습니다.
  Rlog/View/WorkSpace/WorkSpaceCreateConfirmationView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateCreatingScheduleView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateScheduleListView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateView.swift
  Rlog/View/WorkSpace/WorkSpaceListView.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateConfirmationViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateCreatingScheduleViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateScheduleListViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateViewModel.swift
Labels: 리뷰 요청, 어프루브 요청

#90 Bd 182 매월 정산 결과와 근무지 상세 정산 결과 연결
  Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift
  Rlog/View/MonthlyCalculate/MonthlyCalculateListView.swift
Labels: 리뷰 요청

#91 Bd 119 UI 변동사항 간격 컬러 등 반영
  Rlog/View/Components/BorderedTextField.swift
  Rlog/View/Components/InputFormElement.swift
  Rlog/View/Components/ScheduleContainer.swift
  Rlog/View/WorkSpace/WorkSpaceDetailView.swift
  Rlog/View/WorkSpace/WorkSpaceListView.swift
Labels: 리뷰 요청

#92 Bd 185 schedule pending list view UI 디자인 디테일 추가
  Rlog/View/Schedule/ScheduleCreationView.swift
  Rlog/View/Schedule/SchedulePendingListView.swift
Labels: 리뷰 요청

#93 Bd 186 다크모드 지원 막기
  Rlog.xcodeproj/project.pbxproj
  Rlog/View/MainTabView.swift
Labels: 어프루브 요청

#96 BD-131 UI 변동사항 컴포넌트 picker 반영
  Rlog/View/Components/InputFormElement.swift
  Rlog/View/WorkSpace/SubViews/TitleSubView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateConfirmationView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateCreatingScheduleView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateScheduleListView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateView.swift
  Rlog/View/WorkSpace/WorkSpaceDetailView.swift
  Rlog/View/WorkSpace/WorkSpaceListView.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateCreatingScheduleViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateScheduleListViewModel.swift
Labels: 리뷰 요청

#98 BD-190 근무지셀 코너 스트로크 디테일 수정
  Rlog/View/WorkSpace/SubViews/WorkSpaceCell.swift
Labels: 어프루브 요청

#99 BD-191 Custom TabBar 구현
  Rlog.xcodeproj/project.pbxproj
  Rlog/RlogApp.swift
  Rlog/View/MainTabView.swift
  Rlog/View/MonthlyCalculate/MonthlyCalculateListView.swift
  Rlog/ViewModel/ViewRouter.swift
Labels: 리뷰 요청

#100 BD-192 버튼 겹침 현상 수정
  Rlog/View/MainTabView.swift
Labels: 리뷰 요청

#103 BD-193 BorderedPicker 활성화 레이아웃과 애니메이션 / StrokeButton Destruction Type 레이아웃을 개선합니다.
  Rlog/View/Components/BorderedPicker.swift
  Rlog/View/Components/InputFormElement.swift
  Rlog/View/Components/StrokeButton.swift
Labels: 리뷰 요청

#102 Bd 189 core data manager crud 작동 확인
  Rlog/View/Components/ScheduleContainer.swift
  Rlog/View/MonthlyCalculate/MonthlyCalculateListView.swift
  Rlog/View/WorkSpace/SubViews/WorkSpaceCell.swift
  Rlog/View/WorkSpace/WorkSpaceDetailView.swift
  Rlog/View/WorkSpace/WorkSpaceListView.swift
  Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateListViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCellViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateConfirmationViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceDetailViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceListViewModel.swift
Labels: 머지 요청

#105 feat : BD-156 create ScheduleUpdateView
  Rlog.xcodeproj/project.pbxproj
  Rlog/View/Schedule/ScheduleUpdateView.swift
Labels: 머지 요청

#106 Bd 195 근무지 생성 -> 근무 일정 추가 / 수정 로직을 개선합니다.
  Rlog.xcodeproj/project.pbxproj
  Rlog/Assets.xcassets/rlogGreenLogo.imageset/Contents.json
  Rlog/Assets.xcassets/rlogGreenLogo.imageset/rlogGreenLogo.svg
  Rlog/View/Components/BorderedTextField.swift
  Rlog/View/Components/WorkspaceListPicker.swift
  Rlog/View/Components/YearMonthStepperCalendar.swift
  Rlog/View/Schedule/ScheduleCell.swift
  Rlog/View/Schedule/ScheduleCreationView.swift
  Rlog/View/Schedule/ScheduleListView.swift
  Rlog/View/Schedule/ScheduleUpdateView.swift
  Rlog/ViewModel/Schedule/ScheduleCreationViewModel.swift
  Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
  Rlog/ViewModel/Schedule/ScheduleUpdateViewModel.swift
  Rlog/ViewModel/Schedule/TimeManager.swift
Labels: 리뷰 요청

#108 BD-200-schedule-삭제시-has-done-이-false-인-workdays-삭제
  Rlog/CoreData/CoreDataManager.swift
  Rlog/CoreData/DataModel.xcdatamodeld/DataModel.xcdatamodel/contents
Labels: 리뷰 요청

#109 BD-202-workday-toggle-has-done-method-추가
  Rlog/CoreData/CoreDataManager.swift
Labels: 리뷰 요청

#110 BD-206-repeat-days의-transformer를-ns-secure-unarchive-from-data로-변경
  Rlog/CoreData/DataModel.xcdatamodeld/DataModel.xcdatamodel/contents
  Rlog/ViewModel/ViewRouter.swift
Labels: 리뷰 요청

#111 BD-205-탭뷰들의-observed-object를-state-object로-변경
  Rlog/View/Schedule/ScheduleListView.swift
Labels: 리뷰 요청

#112 BD-207-workday-entity를-수정할수-있는-method-추가
  Rlog/CoreData/CoreDataManager.swift
Labels: 리뷰 요청

#114 Bd 201 qa UI 디테일 검수
  Rlog/View/Components/YearMonthStepperCalendar.swift
  Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift
  Rlog/View/MonthlyCalculate/MonthlyCalculateListView.swift
  Rlog/View/Schedule/ScheduleCreationView.swift
  Rlog/View/Schedule/ScheduleListView.swift
  Rlog/View/Schedule/SchedulePendingListView.swift
  Rlog/View/WorkSpace/SubViews/WorkSpaceCell.swift
  Rlog/View/WorkSpace/WorkSpaceDetailView.swift
  Rlog/View/WorkSpace/WorkSpaceListView.swift
Labels: 리뷰 요청

#107 Bd 199 core data manager 초기 설정 workday 관리 로직 추가
  Rlog/CoreData/CoreDataManager.swift
  Rlog/Extension/Date+.swift
  Rlog/View/MainTabView.swift
  Rlog/View/MonthlyCalculate/MonthlyCalculateListView.swift
  Rlog/View/WorkSpace/WorkSpaceListView.swift
  Rlog/ViewModel/MainTabViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateConfirmationViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceDetailViewModel.swift
Labels: 리뷰 요청

#113 Bd 159 coredata 함수 수정에 따른 호출 함수 수정
  Rlog/View/Schedule/ScheduleUpdateView.swift
  Rlog/ViewModel/Schedule/ScheduleUpdateViewModel.swift
Labels: 리뷰 요청

#119 Bd 209 calendar view 그리기
  Rlog/Extension/Date+.swift
  Rlog/Extension/DateFormatter+.swift
  Rlog/Model/WorkDayType.swift
  Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift
  Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateDetailViewModel.swift
Labels: 리뷰 요청

#116 BD-211 ScheduleListViewModel 의 로직명을 개선합니다.
  Rlog/View/Schedule/ScheduleListView.swift
  Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
  Rlog/ViewModel/Schedule/TimeManager.swift
Labels: 머지 요청

#118 Bd 213 schedule cell 리팩토링
  Rlog.xcodeproj/project.pbxproj
  Rlog/Extension/Date+.swift
  Rlog/Manager/TimeManager.swift
  Rlog/Manager/WorkTypeManager.swift
  Rlog/Model/WorkDayType.swift
  Rlog/View/Schedule/ScheduleCell.swift
  Rlog/View/Schedule/ScheduleListView.swift
  Rlog/ViewModel/Schedule/ScheduleCellViewModel.swift
  Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
Labels: 머지 요청

#117 Bd 10 매월 정산 결과를 확인한다
  Rlog/CoreData/CoreDataManager.swift
  Rlog/Extension/Date+.swift
  Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift
  Rlog/View/MonthlyCalculate/MonthlyCalculateListView.swift
  Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateListViewModel.swift
Labels: 리뷰 요청

#125 Bd 225 메인 탭 바에 줄 삭제
  Rlog/View/MainTabView.swift
Labels: 리뷰 요청

#126 Bd 226 근무 생성 뒤로 가기 버튼 수정
  Rlog/View/WorkSpace/WorkSpaceCreateConfirmationView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateScheduleListView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateView.swift
Labels: 리뷰 요청

#124 BD-220 근무 일정 생성 프로세스를 개선합니다.
  Rlog/View/Components/WorkspaceListPicker.swift
  Rlog/View/Schedule/ScheduleCreationView.swift
  Rlog/View/Schedule/ScheduleListView.swift
  Rlog/ViewModel/Schedule/ScheduleCreationViewModel.swift
Labels: 리뷰 요청

#120 BD-214 미확정 일정 모아보기 화면의 기본 레이아웃을 작성합니다.
  Rlog.xcodeproj/project.pbxproj
  Rlog/Extension/Sequence+.swift
  Rlog/View/Schedule/SchedulePendingListView.swift
  Rlog/ViewModel/Schedule/ScheduleCellViewModel.swift
  Rlog/ViewModel/Schedule/SchedulePendingListViewModel.swift
Labels: 리뷰 요청

#122 Bd 217 메인화면에서 확인 로직 구현
  Rlog/View/Schedule/ScheduleCell.swift
  Rlog/View/Schedule/ScheduleListView.swift
  Rlog/View/Schedule/SchedulePendingListView.swift
  Rlog/ViewModel/Schedule/ScheduleCellViewModel.swift
Labels: 리뷰 요청

#132 Bd 212 디자인 검수
  Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift
  Rlog/View/Schedule/ScheduleCreationView.swift
  Rlog/View/Schedule/ScheduleListView.swift
  Rlog/View/Schedule/ScheduleUpdateView.swift
  Rlog/View/WorkSpace/WorkSpaceDetailView.swift
Labels: 어프루브 요청

#129 Bd 227 work type manager 로직 검증 및 수정
  Rlog.xcodeproj/project.pbxproj
  Rlog/Manager/TimeManager.swift
  Rlog/Manager/WorkTypeManager.swift
  Rlog/Model/WorkDayType.swift
  Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift
  Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateCellViewModel.swift
  Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateDetailViewModel.swift
  Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateListViewModel.swift
  Rlog/ViewModel/Schedule/ScheduleCellViewModel.swift
Labels: 리뷰 요청

#137 Bd 215 calendar detail view 로직 구현하기
  Rlog.xcodeproj/project.pbxproj
  Rlog/Manager/TimeManager.swift
  Rlog/Manager/WorkTypeManager.swift
  Rlog/Model/WorkDayType.swift
  Rlog/View/MonthlyCalculate/MonthlyCalculateCellView.swift
  Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateCellViewModel.swift
  Rlog/ViewModel/Schedule/ScheduleCellViewModel.swift
Labels: 리뷰 요청

#130 Bd 231 주간 변동 시 날짜에 맞게 자동으로 일정 변경
  Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
Labels: 리뷰 요청

#131 Bd 224 주휴수당 로직 수정
  Rlog.xcodeproj/project.pbxproj
  Rlog/Model/MonthlyCalculateResult.swift
  Rlog/View/MonthlyCalculate/MonthlyCalculateListView.swift
  Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateListViewModel.swift
Labels: 리뷰 요청

#134 Bd 229 확정된 근무셀 UI구현 선택 비활성화
  Rlog/View/Schedule/ScheduleCell.swift
  Rlog/View/Schedule/ScheduleListView.swift
Labels: 리뷰 요청

#138 BD-234 근무 삭제 시 크래시가 발생하는 에러를 수정합니다.
  Rlog/View/Schedule/ScheduleCell.swift
  Rlog/ViewModel/Schedule/ScheduleCellViewModel.swift
Labels: 리뷰 요청

#139 BD-235 MonthlyCalculateDetailView
  Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift
  Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateDetailViewModel.swift
Labels: 리뷰 요청

#141 BD-237-navigaiton-gesture-안-먹는-현상
  Rlog.xcodeproj/project.pbxproj
  Rlog/Extension/UINavigationController+.swift
Labels: 리뷰 요청, Conflict 발생

#142 Bd 236 같은 월이라도 미확정 일정이 있을 때만 indicator 색깔이 primary
  Rlog/Extension/UINavigationController+.swift
  Rlog/View/Schedule/ScheduleListView.swift
  Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
Labels: 리뷰 요청

#143 BD-238-define-work-type-로직-수정
  Rlog/Manager/WorkTypeManager.swift
Labels: 추가기능 구현중

#145 BD-240-define-work-type-로직-수정
  Rlog/Manager/WorkTypeManager.swift
Labels: 리뷰 요청

#146 BD 241 미확정 근무 일정 표시되지 않는 사항을 개선합니다
  Rlog.xcodeproj/project.pbxproj
  Rlog/View/Schedule/ScheduleHasNotDoneListView.swift
  Rlog/View/Schedule/ScheduleListView.swift
  Rlog/ViewModel/Schedule/ScheduleHasNotDoneListViewModel.swift
Labels: 리뷰 요청

#148 Bd 144 상세 정보 바인딩
  Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift
  Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateDetailViewModel.swift
Labels: 리뷰 요청

#149 BD-245 근무패턴 없을경우 다음버튼 비활성화 처리
  Rlog/ViewModel/WorkSpace/WorkspaceCreateScheduleListViewModel.swift
Labels: 리뷰 요청

#150 Bd 243 근무지 정보 입력 시 예외처리
  Rlog/View/Components/BorderedTextField.swift
  Rlog/View/WorkSpace/WorkspaceCreateView.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateViewModel.swift
Labels: 리뷰 요청

#151 BD-246 근무패턴 컴포넌트화
  Rlog/View/WorkSpace/WorkspaceCreateScheduleListView.swift
Labels: 리뷰 요청

#153 BD-247 근무패턴 생성시 예외처리 적용
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateCreatingScheduleViewModel.swift
Labels: 리뷰 요청

#152 Bd 244 동일 시간 추가 근무 생성 제한
  Rlog/Model/WorkDayType.swift
  Rlog/View/MonthlyCalculate/MonthlyCalculateCellView.swift
  Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift
  Rlog/View/Schedule/ScheduleCell.swift
  Rlog/View/Schedule/ScheduleCreationView.swift
  Rlog/ViewModel/Schedule/ScheduleCreationViewModel.swift
Labels: 리뷰 요청

#154 BD-249 주휴수당 소득세 UI 순서바꾸기
  Rlog/View/WorkSpace/WorkspaceCreateView.swift
  Rlog/View/WorkSpace/WorkspaceDetailView.swift
Labels: 리뷰 요청

#147 Bd 242 time picker 컴포넌트의 포커스를 핸들링합니다
  Rlog/View/Components/BorderedPicker.swift
  Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift
  Rlog/View/Schedule/ScheduleCreationView.swift
  Rlog/View/Schedule/ScheduleUpdateView.swift
  Rlog/View/WorkSpace/WorkspaceCreateCreatingScheduleView.swift
  Rlog/ViewModel/Schedule/ScheduleCreationViewModel.swift
  Rlog/ViewModel/Schedule/ScheduleUpdateViewModel.swift
Labels: 머지 요청

#155 feat : BD-146 화면 캡쳐 및 공유 기능을 구현합니다.
  Rlog.xcodeproj/project.pbxproj
  Rlog/Extension/View+.swift
  Rlog/View/Components/ShareSheet.swift
  Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift
  Rlog/ViewModel/MonthlyCalculate/MonthlyCalculateDetailViewModel.swift
Labels: 리뷰 요청

#156 Bd 248 겹치는 스케줄이 없는지 확인하기
  Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift
  Rlog/View/WorkSpace/WorkspaceCreateCreatingScheduleView.swift
  Rlog/View/WorkSpace/WorkspaceDetailView.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateCreatingScheduleViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceDetailViewModel.swift
Labels: 머지 요청

#157 Bd 250 근무지가 없을 때 근무 생성 버튼 비활성화
  Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift
  Rlog/View/Schedule/ScheduleCreationView.swift
  Rlog/View/Schedule/ScheduleListView.swift
  Rlog/View/Schedule/ScheduleUpdateView.swift
  Rlog/ViewModel/Schedule/ScheduleCreationViewModel.swift
  Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
  Rlog/ViewModel/Schedule/ScheduleUpdateViewModel.swift
Labels: 리뷰 요청

#159 feat : BD-253 세금 표현시 -를 표시합니다.
  Rlog/View/MonthlyCalculate/MonthlyCalculateDetailView.swift
Labels: 리뷰 요청

#121 BD-210 readme작성
  README.md
  개인정보 처리방침.md
Labels: 추가기능 구현중
