Repository DeveloperAcademy-POSTECH/MacC-Team-Bremen-DD, pull requests merged in 2022-10, with the labels that each got.

#9 feat : BD-16 근무지 / 근무 일정 관리를 위한 StrokeButton을 구현합니다.
  Rlog.xcodeproj/project.pbxproj
  Rlog/View/Components/StrokeButton.swift
Labels: 머지 요청

#8 Bd 31 근무지 리스트 UI 구현
  Rlog.xcodeproj/project.pbxproj
  Rlog/View/WorkSpace/SubViews/WorkSpaceCell.swift
  Rlog/View/WorkSpace/WorkSpaceListView.swift
Labels: 머지 요청

#6 feat : BD-3 CoreData 설정 및 method
  Rlog.xcodeproj/project.pbxproj
  Rlog/CoreData/CoreDataManager.swift
  Rlog/CoreData/DataModel.xcdatamodeld/Rlog.xcdatamodel/contents
  Rlog/Model/AlbaStatus.swift
  Rlog/Model/CoreData.swift
  Rlog/Model/DataModel/ScheduleEntity+CoreDataClass.swift
  Rlog/Model/DataModel/ScheduleEntity+CoreDataProperties.swift
  Rlog/Model/DataModel/WorkDayEntity+CoreDataClass.swift
  Rlog/Model/DataModel/WorkDayEntity+CoreDataProperties.swift
  Rlog/Model/DataModel/WorkspaceEntity+CoreDataClass.swift
  Rlog/Model/DataModel/WorkspaceEntity+CoreDataProperties.swift
  Rlog/Model/DayEntity.swift
  Rlog/Model/ScheduleEntity.swift
  Rlog/Model/WeekDay.swift
  Rlog/Model/WorkspaceColor.swift
  Rlog/Model/WorkspaceEntity.swift
  Rlog/Rlog.entitlements
  Rlog/View/Components/FilledButton.swift
  Rlog/View/Components/StrokeButton.swift
  Rlog/View/MainTabView.swift
  Rlog/View/WorkSpace/SubViews/WorkSpaceCell.swift
  Rlog/View/WorkSpace/WorkSpaceListView.swift
  Rlog/ViewModel/MainTabViewModel.swift
Labels: 머지 요청

#20 BD-69-core-data-추가
  Rlog.xcodeproj/project.pbxproj
  Rlog/CoreData/CoreDataManager.swift
  Rlog/CoreData/DataModel.xcdatamodeld/Rlog.xcdatamodel/contents
  Rlog/Model/CoreData/CoreData.swift
  Rlog/Model/CoreData/ScheduleEntity+CoreDataClass.swift
  Rlog/Model/CoreData/ScheduleEntity+CoreDataProperties.swift
  Rlog/Model/CoreData/WorkDayEntity+CoreDataClass.swift
  Rlog/Model/CoreData/WorkDayEntity+CoreDataProperties.swift
  Rlog/Model/CoreData/WorkspaceEntity+CoreDataClass.swift
  Rlog/Model/CoreData/WorkspaceEntity+CoreDataProperties.swift
  Rlog/Model/WeekDay.swift
  Rlog/Model/WorkspaceColor.swift
  Rlog/View/MainTabView.swift
Labels: 리뷰 요청, 머지 요청

#14 BD-16 최종 PR 리뷰 결과에 따라 코드를 리팩토링 합니다.
  Rlog/View/Components/StrokeButton.swift
Labels: 리뷰 요청, Conflict 발생

#27 Bd 25 근무지 등록 UI 구현
  Rlog.xcodeproj/project.pbxproj
  Rlog/Rlog.entitlements
  Rlog/View/WorkSpace/WorkSpaceCreateView.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateViewModel.swift
Labels: 머지 요청

#22 BD-71-core-data-attributes-수정
  Rlog/CoreData/CoreDataManager.swift
  Rlog/CoreData/DataModel.xcdatamodeld/Rlog.xcdatamodel/contents
  Rlog/Model/CoreData/ScheduleEntity+CoreDataProperties.swift
  Rlog/Model/CoreData/WorkDayEntity+CoreDataProperties.swift
Labels: 리뷰 요청

#10 BD-17 CustomTextField, CustomTextFieldContainer를 구현합니다.
  Rlog.xcodeproj/project.pbxproj
  Rlog/View/Components/InputFormElement.swift
  Rlog/View/Components/UnderlinedTextField.swift
Labels: 머지 요청, 어프루브 요청

#12 [FEAT] BD-37 스케줄 수정 UI 구현
  Rlog/View/Schedule/ScheduleUpdateView.swift
  Rlog/ViewModel/Schedule/ScheduleUpdateViewModel.swift
Labels: 어프루브 요청

#15 Bd 32 근무지 수정 UI 구현
  Rlog/View/WorkSpace/SubViews/WorkSpaceCell.swift
  Rlog/View/WorkSpace/WorkSpaceDetailView.swift
  Rlog/View/WorkSpace/WorkSpaceListView.swift
Labels: 리뷰 요청, 어프루브 요청

#16 Bd 38 스케줄 추가 UI 구현
  Rlog/View/Schedule/ScheduleCreateView.swift
  Rlog/ViewModel/Schedule/ScheduleCreateViewModel.swift
Labels: 리뷰 요청

#23 Bd 58 디바이더 만들기
  Rlog.xcodeproj/project.pbxproj
  Rlog/View/Components/HDivider.swift
Labels: 리뷰 요청

#26 BD-72-등록확인ui구현-머지용-브랜치-추가(DB-28)
  Rlog.xcodeproj/project.pbxproj
  Rlog/View/WorkSpace/SubViews/TitleSubView.swift
  Rlog/View/WorkSpace/SubViews/WorkSpaceInfoSubView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateConfirmationView.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateConfirmationViewModel.swift
Labels: 어프루브 요청

#25 Bd 36 cell UI 구현
  Rlog/Extension/ScheduleListView+.swift
  Rlog/View/Schedule/ScheduleListView.swift
Labels: 리뷰 요청

#18 BD-26-근무-유형-리스트-ui-구현
  Rlog.xcodeproj/project.pbxproj
  Rlog/View/WorkSpace/WorkSpaceCreateCreatingScheduleView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateScheduleListView.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateCreatingScheduleViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateScheduleListViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateViewModel.swift
Labels: 리뷰 요청

#29 feat : BD-74 ScheduleContainer를 구현합니다.
  Rlog.xcodeproj/project.pbxproj
  Rlog/View/Components/ScheduleContainer.swift
Labels: 리뷰 요청

#30 Bd 68 이미지 뷰 대체 선정 정산 화면
  Rlog.xcodeproj/project.pbxproj
  Rlog/Assets.xcassets/Wip.imageset/Contents.json
  Rlog/Assets.xcassets/Wip.imageset/wipImage.png
  Rlog/View/MonthlyCalculate/MonthlyCalculateListView.swift
  Rlog/View/MonthlyCalculate/WIPView.swift
Labels: 리뷰 요청

#31 Bd 44 work space create 과정 뷰 연결하기
  Rlog.xcodeproj/project.pbxproj
  Rlog/Model/CreatingScheduleModel.swift
  Rlog/Model/CreatingWorkSpaceModel.swift
  Rlog/View/WorkSpace/SubViews/TitleSubView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateConfirmationView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateCreatingScheduleView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateScheduleListView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateView.swift
  Rlog/View/WorkSpace/WorkSpaceListView.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateConfirmationViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateCreatingScheduleViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateScheduleListViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateViewModel.swift
Labels: 리뷰 요청

#28 BD-73-근무지-뷰모델-작성
  Rlog.xcodeproj/project.pbxproj
  Rlog/Assets.xcassets/ContainerBackground.colorset/Contents.json
  Rlog/CoreData/CoreDataManager.swift
  Rlog/CoreData/DataModel.xcdatamodeld/Rlog.xcdatamodel/contents
  Rlog/Extension/Color+.swift
  Rlog/Extension/NSNotification+.swift
  Rlog/View/WorkSpace/SubViews/WorkSpaceCell.swift
  Rlog/View/WorkSpace/WorkSpaceCreateView.swift
  Rlog/View/WorkSpace/WorkSpaceDetailView.swift
  Rlog/View/WorkSpace/WorkSpaceListView.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCellViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceDetailViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceListViewModel.swift
Labels: 리뷰 요청, 추가기능 구현중

#33 BD-17 CustomTextField의 parameter 타입을 generic 으로 변경합니다.
  Rlog/View/Components/InputFormElement.swift
  Rlog/View/Components/UnderlinedTextField.swift
Labels: 리뷰 요청

#35 BD-80-앱-로고-디자인-적용
  Rlog/Assets.xcassets/AppIcon.appiconset/Contents.json
  Rlog/Assets.xcassets/AppIcon.appiconset/RlogLogo.png
  Rlog/Assets.xcassets/AppIcon.appiconset/sampleLogo.png
Labels: 리뷰 요청

#34 BD-79-뷰모델-코어데이터-연동
  Rlog/CoreData/CoreDataManager.swift
  Rlog/CoreData/DataModel.xcdatamodeld/Rlog.xcdatamodel/contents
  Rlog/Extension/DateFormatter+.swift
  Rlog/Model/CoreData/ScheduleEntity+CoreDataProperties.swift
  Rlog/Model/CreatingScheduleModel.swift
  Rlog/Model/CreatingWorkSpaceModel.swift
  Rlog/Model/WorkspaceColor.swift
  Rlog/View/Components/CustomButtonView.swift
  Rlog/View/Components/HDivider.swift
  Rlog/View/Components/InputFormElement.swift
  Rlog/View/Components/ScheduleContainer.swift
  Rlog/View/Components/StrokeButton.swift
  Rlog/View/Components/UnderlinedTextField.swift
  Rlog/View/WorkSpace/WorkSpaceCreateConfirmationView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateCreatingScheduleView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateScheduleListView.swift
  Rlog/View/WorkSpace/WorkSpaceCreateView.swift
  Rlog/View/WorkSpace/WorkSpaceDetailView.swift
  Rlog/View/WorkSpace/WorkSpaceListView.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCellViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateConfirmationViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateCreatingScheduleViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateScheduleListViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceDetailViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceListViewModel.swift
Labels: 리뷰 요청, 추가기능 구현중

#39 Bd 83 근무지 수정 삭제 alert
  Rlog/View/WorkSpace/WorkSpaceDetailView.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceDetailViewModel.swift
Labels: 리뷰 요청, 어프루브 요청

#38 Bd 39 스케줄 추가 로직 구현
  Rlog/View/Schedule/ScheduleCreateView.swift
  Rlog/ViewModel/Schedule/ScheduleCreateViewModel.swift
Labels: 어프루브 요청

#32 Bd 46 메인 화면 로직 구현
  Rlog/Assets.xcassets/GradientGray.colorset/Contents.json
  Rlog/Assets.xcassets/StrokeGray.colorset/Contents.json
  Rlog/Extension/Color+.swift
  Rlog/Extension/Date+.swift
  Rlog/Extension/ScheduleListView+.swift
  Rlog/View/Schedule/ScheduleCreateView.swift
  Rlog/View/Schedule/ScheduleListView.swift
  Rlog/View/Schedule/ScheduleUpdateView.swift
  Rlog/ViewModel/Schedule/ScheduleCreateViewModel.swift
  Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
  Rlog/ViewModel/Schedule/ScheduleUpdateViewModel.swift
Labels: 어프루브 요청

#40 BD-88-hot-fix
  Rlog.xcodeproj/project.pbxproj
  Rlog/Extension/NSNotification+.swift
  Rlog/Extension/Notification+.swift
  Rlog/View/WorkSpace/WorkSpaceCreateConfirmationView.swift
  Rlog/View/WorkSpace/WorkSpaceDetailView.swift
  Rlog/View/WorkSpace/WorkSpaceListView.swift
  Rlog/ViewModel/Schedule/ScheduleListViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceCreateConfirmationViewModel.swift
  Rlog/ViewModel/WorkSpace/WorkSpaceListViewModel.swift
Labels: 어프루브 요청

#43 feat : BD-92 UITabBar 컬러 추가
  Rlog/View/MainTabView.swift
Labels: 리뷰 요청

#44 Bd 90 테스트 플라이트 배포 및 프로비져닝 세팅
  Rlog.xcodeproj/project.pbxproj
  Rlog.xcodeproj/xcshareddata/xcschemes/Rlog.xcscheme
  Rlog/Rlog.entitlements
Labels: 머지 요청, 어프루브 요청
